language: objective-c
osx_image: xcode7.2
script:
      - xcodebuild -workspace JWAnimatedImage.xcworkspace -scheme 'JWAnimatedImageExample’ -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=latest' test

